on: 
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::httr 
            any::jsonlite
            any::rvest

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: main_folder
          ref: main

      - name: Create and populate credentials file with secrets
        working-directory: ./main_folder
        run: |
          echo '.slack_workflow_trigger_url="'"$MAPPED_SLACK_WEBHOOK"'"' >> credentials.R
        shell: bash
        env:
          MAPPED_SLACK_WEBHOOK : ${{ secrets.SLACK_WEBHOOK }}

      - name: Get data and produce JSON
        working-directory: ./main_folder
        run: |
          Rscript run.R
